FROM ubuntu:latest
LABEL authors="marky"

ENTRYPOINT ["top", "-b"]

advanced rotation {
    do polar bypass gcd fix
    do mainframe
    do fpu
    do cache
    do mmx
    do sse
    do sse2
    do sse3
    do ssse3
    do sse4_1
    do sse4_2
    do avx
    do avx2
    do avx512f
    loop (
        do hyperthreading
        do turbo
    )
    do virtualization
    do aes
    do sha
    do crc32
}